### ISSUE TITLE
[feature] PersistentArray mapping for PostgreSQL typed arrays

### ISSUE THREAD

**Issue by atangsutisna** [JadiraOrg/jadira#21]
[PostgreSQL has typed array data type](http://www.postgresql.org/docs/9.3/static/arrays.html) ([Oracle has VARARRAY too](http://www.dba-oracle.com/tips_oracle_varray.htm)), that can be used with any data type: `varchar`, `boolean`, `numeric`, `type` (enum), etc.

It can then be mapped to a `@Entity` or `@Embeddable' attribute using:
1. object arrays: `Object[]`, `String[]`, `Boolean[]`, ...
2. primitive arrays: `int[]`, `boolean[]`, ...
3. `Collection<>`: `Set<>`, `List<>`. Some people might want to use `Deque<>` too.

`Vector<>` / `Stack<>` is probably an edge case that no one uses.

Note the element type may be an `Enum` that in turn is mappable to either `String`, numeric, or a custom data type (`CREATE TYPE ... AS ENUM` in PostgreSQL).

References:
1. http://stackoverflow.com/a/13407270
2. http://stackoverflow.com/a/21984484

**Comment by chrisphe** [comment]
Keeping this open for now, still considering whether to include

**Comment by chrisphe** [comment]
In the absence of a more complete PR, I propose to close this.
