### ISSUE TITLE
Support for ThreeTen Backport 1.0 (with JDK6)

### ISSUE THREAD

**Issue by DerEineDa** [JadiraOrg/jadira#25]
Since a few days ThreeTen BP 1.0 is available and provides support for JDK 6, which we need.

I compiled Jadira on my own and it seems trivial to support JDK 6, as the only reason it doesn't compile right now is the usage of integer literals using underscores (1_000 instead of 1000) and two switch-statements using Strings.

Best regards
Christian

**Comment by chrisphe** [comment]
About to Push change to HEAD. Please note that the support classes are moving from usertype.extended to usertype.core
