### ISSUE TITLE
ConfigurationHelper leaks memory when SessionFactory is closed.

### ISSUE THREAD

**Issue by kidnme** [JadiraOrg/jadira#26]
When the session factory is closed, the integrator calls the ConfigurationHelper configureDefaultProperties() with a null set of properties.  This causes the session factory to be removed from the DEFAULT_PROPERTIES hash, but not from the JDBC 42 hash.  Repeated invocations of the Configuration Helper (as in unit tests that recreate the database and the session factory) will continue to add new session factories to the JDBC 42 hash - thus running large unit test suites out of memory.

**Comment by chrisphe** [comment]
Will be resolved shortly in HEAD
