### ISSUE TITLE
BigMoney and number of decimal places

### ISSUE THREAD

**Issue by FrEaKmAn** [JadiraOrg/jadira#27]
Based on the description of BigMoney, I'm able to store a number with unrestricted decimal place precision or at least with 5 decimal places. Using BigMoney with Jadira and PostgreSQL still creates column with type decimal(19, 2).

    @Entity
    @Table(name = "sensors")
    @TypeDef(name = "MoneyAmountWithCurrencyType", typeClass = PersistentBigMoneyAmountAndCurrency.class)
    public class Factory
    {
        @Columns(columns = { @Column(name = "electricity_cost_currency", nullable = false), @Column(name = "electricity_cost", nullable = false) })
        @org.hibernate.annotations.Type(type = "MoneyAmountWithCurrencyType")
        public BigMoney electricityCost;
    }

This is my entity. Should I use some other Persistant..? or should I alter @Column(columnDefinition)?

**Comment by chrisphe** [comment]
Try using @Column(columnDefinition="..."...

Regards Chris
