### ISSUE TITLE
Jadira usertype.core and usertype.spi have compile dependency on junit

### ISSUE THREAD

**Issue by sebdotv** [JadiraOrg/jadira#32]
These compile dependencies on junit are transitively inherited by projects that depend on Jadira usertype: 
https://github.com/JadiraOrg/jadira/blob/master/usertype.core/pom.xml#L83
https://github.com/JadiraOrg/jadira/blob/master/usertype.spi/pom.xml#L99

If possible, these dependencies should be changed to scope test, or if they're used for compilation, they could be changed to provided.

**Comment by chrisphe** [comment]
If you do an mvn dependency:tree on the projects you will see the dependency is managed as test scope. I believe this issue is invalid
