### ISSUE TITLE
Leaked Connection in AbstractUserTypeHibernateIntegrator

### ISSUE THREAD

**Issue by mattj65817** [JadiraOrg/jadira#34]
`AbstractUserTypeHibernateIntegrator` in `usertype.spi` version 3.2.0.GA causes a connection leak on startup if the `jadira.usertype.useJdbc42Apis` property is not explicitly configured.  The problem occurs on line 80:

    if (JavaVersion.getMajorVersion() >= 1 && JavaVersion.getMinorVersion() >= 8) {
    try {
        DatabaseMetaData dmd = sessionFactory.getJdbcServices().getConnectionProvider().getConnection().getMetaData();
        int driverMajorVersion = dmd.getDriverMajorVersion();
        ...
    }

As you can see, `ConnectionProvider.getConnection()` is called, but `Connection.close()` is not called after the connection metadata is retrieved.

I use a very small connection pool in development, and I noticed this because the pool would exhaust during startup, causing a connection timeout the third or fourth time this method is called.  It was not easy to track down.

I believe everything should be fine if the code is modified to close the connection.

Until the problem is fixed, it can be worked around by explicitly setting `jadira.usertype.useJdbc42Apis` to `true` or `false` so that the metadata interrogation does not occur.

**Comment by kherrala** [comment]
This seems to be fixed in #16 but the fix has not yet been released.

**Comment by mattj65817** [comment]
Thank you. I've updated my internal documentation to refer to #16 instead. Closing this issue.
