### ISSUE TITLE
DateColumnLocalDateMapper fromNonNullValue and toNonNullValue methods don't honor database timezone setting 

### ISSUE THREAD

**Issue by joeydaowang** [JadiraOrg/jadira#35]
First, thank you so much for the amazing framework. 

After our project upgrade jadira from 3.1.0.CR8 to 3.2.0.GA, we have issue of convert localDate to Date. We have both Sql Server database and Java Applicatoin running on 'NZ' timezone, and we set both 'jadira.usertype.databaseZone' and 'jadira.usertype.javaZone' to 'UTC'. After upgrade to 3.2.0.GA  we found the date type column will be the localDate value minus one day. e.g. try to update one date column with localDate '2015-03-27' then the value insert into database is actually '2015-03-26'

After I checked the source code of jadira, I found the fromNonNullValue and toNonNullValue methods of DateColumnLocalDateMapper don't really respect the databaseZone. e.g. fromNonNullValue method is
    @Override
    public Date toNonNullValue(LocalDate value) {

```
    if (databaseZone == null) {
        return Date.valueOf(LOCAL_DATE_FORMATTER.print((LocalDate) value));
    }

    DateTime zonedValue = value.toDateTime(value.toDateTimeAtStartOfDay());

    final Date date = new Date(zonedValue.getMillis());
    return date;
}
```

it is not a problem if jadira does the same as 3.1.0.CR8 that using 'PreparedStatement.setDate(index, javaTypeDescriptor.unwrap...)' to set date value. However new version jadira using 'PreparedStatement.setDate(index, javaTypeDescriptor.unwrap...,Calendar), and here the Calendar holds the TZ information which is 'jadira.usertype.databaseZone' setting.

I am not sure whether I explain the problem correctly, or I understand jadira correctly. It would be great if someone could give some feedback. Thanks.

**Comment by chrisphe** [comment]
I can look at bringing in the old behaviour (3.1.0.CR8) where Jadira attempts to perform the DB zone conversion itself rather than relying on the overloaded setDate() with a property to choose which behaviour to use? Would this work as an approach (I don't think the old behaviour works across all databases either)?

**Comment by chrisphe** [comment]
#24 demonstrates a possible issue with the old approach

**Comment by joeydaowang** [comment]
Thanks for the response.
But the issue you mentioned above is about DateTime, the issue I found is about LocalDate.

**Comment by adammichalik** [comment]
We're facing the same issue with LocalDate entity property + Jadira 3.2.0.GA + Oracle 11.2.0.4.

We have explicit setting of
```
jadira.usertype.javaZone=UTC
jadira.usertype.databaseZone=UTC
```

What happens in `DateColumnLocalDateMapper#toNonNullValue` is:

```java
    public Date toNonNullValue(LocalDate value) {

        if (databaseZone==null) { // databaseZone is set explicitly to UTC
        	return Date.valueOf(LOCAL_DATE_FORMATTER.print((LocalDate) value));
        }

    	DateTime zonedValue = value.toDateTime(value.toDateTimeAtStartOfDay());
        /*
         value.toDateTimeAtStartOfDay() creates a DateTime in the default TZ
         The outcome is
         zonedValue = 2015-01-01T00:00:00.000+01:00
         ie. midnight with your default TZ offset
         Is the value.toDateTime(...) wrapper necessary?
        */

        final Date date = new Date(zonedValue.getMillis());
        /*
        date is 2015-01-01, but underneath the GregorianCalendar preserves the default TZ offset
        2015-01-01T00:00:00.000+0100
        which in UTC is
        2014-12-31T23:00:00.000Z
        ie. one day earlier
        */
        return date;
    }
```
The following snippet exposes the problem and suggests the fix by providing the `databaseZone` to the `value.toDateTimeAtStartOfDay()` call.
```java
    @Test
    public void useDbTimeZoneForLocalDate() {
        DateColumnLocalDateMapper mapper = new DateColumnLocalDateMapper(UTC);

        Date date = mapper.toNonNullValue(new LocalDate("2015-01-01", UTC));

        assertThat(date).isEqualTo(new DateTime("2015-01-01T00:00:00Z", UTC).toDate());
    }

    @Test
    public void useDbTimeZoneForLocalDateFixed() {
        Date date = toNonNullValueFixed(new LocalDate("2015-01-01", UTC));

        assertThat(date).isEqualTo(new DateTime("2015-01-01T00:00:00Z", UTC).toDate());
    }


    public Date toNonNullValueFixed(LocalDate value) {
        DateTimeZone databaseZone = UTC;
        // this snippet fixes the original implementation
        if (databaseZone==null) {
            return Date.valueOf(LOCAL_DATE_FORMATTER.print((LocalDate) value));
        }

        DateTime zonedValue = value.toDateTime(value.toDateTimeAtStartOfDay(databaseZone)); // use databaseZone

        final Date date = new Date(zonedValue.getMillis());
        return date;
    }
```

**Comment by palakmathur** [comment]
We are having the same issue. While inserting into a DateTime column in SQL Server, LocalDate is saved as UTC DateTime even jadira.usertype.javaZone and jadira.usertype.databaseZone JPA properties are set to Central time zone.  

usertype.core version : 3.2.0.GA
database used: SQL Server 2008
JPA Properties:
                <prop key="jadira.usertype.javaZone">America/Chicago</prop>
        <prop key="jadira.usertype.databaseZone">America/Chicago</prop>

Upon debugging found that jadira.usertype.databaseZone is not being considered when LocalDate is converted to a zoned Datetime. The cause of the issue is at the following location:

Class: org.jadira.usertype.dateandtime.joda.columnmapper.DateColumnLocalDateMapper
Method : 
   public Date toNonNullValue(LocalDate value)

**Comment by chrisphe** [comment]
Pleae advise if you are still seeing this in 4.x or 5.x releases. Thankyou

**Comment by palakmathur** [comment]
@chrisphe  I don't think the issue is resolved. If you see method toNonNullValue(), it still do not consider "databaseZone". However, I will try using 5.x release and let you.

**Comment by joeydaowang** [comment]
I verified this issue in Jadira 5.0.0.GA with Hibernate 5.0.7.Final under Wildfly 10.0.0.Final. The same issue exists in Jadira 5.0.0.GA.

**Comment by danwatt** [comment]
Same issue Jadira 5.0.0.GA with Hibernate 4.3.11 and SQL Server (MS driver)

**Comment by chrisphe** [comment]
The next build will remove databaseZone in favour of using the Hibernate parameter. You'll still be able to set Java Zone in some cases.

**Comment by chrisphe** [comment]
I've reinstated databaseZone, but it now delegates to Hibernate to handle (by proxying the resolution of the TimeZone from the session). This means it overrides the Hibernate property, but it also means the database zone must be specified using JDK TimeZone format in all cases.

**Comment by palakmathur** [comment]
@chrisphe which version should we use?

**Comment by palakmathur** [comment]
And Thank you so much!

**Comment by chrisphe** [comment]
I've not released this yet, but will be released in the next few days hopefully. There's one open issue I'm looking at.
