### ISSUE TITLE
PersistentDateTimeAndZone saves incorrect timestamp if using type `timestamp with time zone` (PostgreSQL)

### ISSUE THREAD

**Issue by Antonnz** [JadiraOrg/jadira#37]
With the following field:

```
@Basic()
@Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTimeAndZone")
@Columns(columns = { @Column(name = "creationtime", nullable = false),
        @Column(name = "creationtimezone", nullable = false) })
private DateTime creationTime = null;
```

and the column definitions:
- `creationtime timestamp with time zone,` // note: **with time zone**
- `creationtime_zone varchar(255)`

`PersistentDateTimeAndZone` saves the `DateTime` `2015-05-28 14:43:24.209+07:00` incorrectly as:
- creationtime: `2015-05-28 12:43:24.209-00:00` (`2015-05-28 17:43:24.209+07:00`)
- creationtime_zone: `Asia/Jakarta`

While `PersistentDateTimeAndZone` works fine with `timestamp` type, it's sometimes preferred to always use `timestamp with timezone`, therefore in which case `PersistentDateTimeAndZone` should save it as:
- creationtime: `2015-05-28 07:43:24.209-00:00` (`2015-05-28 14:43:24.209+07:00`)
- creationtime_zone: `Asia/Jakarta`

Tag @ceefour

**Comment by chrisphe** [comment]
I think it could be possible to support this via a new usertype. JDBC itself doesn't have built in support for this type, you would need to see if you can map it e.g. via PGObject. Have a look at this (resolved) issue which maps an enumerated type for Postgres in this way #14

If you are interested to work on this, I am happy to assist with integrating it into the library

**Comment by chrisphe** [comment]
Closing old issue
