### ISSUE TITLE
Support JSR 354

### ISSUE THREAD

**Issue by keilw** [JadiraOrg/jadira#38]
As @chrisphe was also in the JSR 354 EG, this JSR now Final at 1.0 seems like a good time to consider support for it here. Unlike Date/Time where nearly a dozen alternatives are offered (JodaTime, java.time, ThreeTenBP plus several others from the JDK;-) JodaMoney just is not accepted by the community. I see DateTime usage in projects by financial service providers usually backed by JodaTime, but they prefer BigDecimal and see no use in JodaMoney. Having an official Java standard now this could likely change for JSR 354, so supporting it sounds appealing to Jadira.

**Comment by chrisphe** [comment]
Its definitely going to be updated, there is an integration in there but needs to be revisited as it was done quite some time ago

See

https://github.com/JadiraOrg/jadira/tree/master/usertype.extended/src/main/java/org/jadira/usertype/moneyandcurrency/moneta

**Comment by keilw** [comment]
Maybe @otaviojava could help with that? He suggested "JEE essentials" for Moneta/JavaMoney, but where there's other frameworks already used by the community (we heard, Spring even considers using it in upcoming releases;-) it sounds better to do it there.

**Comment by chrisphe** [comment]
Messed up some imports during refactoring

**Comment by chrisphe** [comment]
I think extended now will work with both Moneta and Moneta BP due to the use of retroweaver, otherwise we have a more complex problem. I'm closing the issue but would welcome any testing / validation by others ahead of making the next Jadira release.

**Comment by otaviojava** [comment]
Yes, the Java EE would just the first step.
The main idea is has a project to integration, maybe call its of midas, and this project has sub-modules, and each sub-modules integration with a framework, such CDI, Spring, Juice, etc.

**Comment by keilw** [comment]
We could create one or the other JavaMoney sub-project, but e.g. Jadira seems accepted by commercial projects, just saw (only the JodaTime aspect, nobody uses SE 8 here yet ;-) it used in the "BOM" of a current client's project. So I would leave those to projects like Jadira, Spring* or similar that wish to support it. If there's anything missing, we may think about JavaMoney projects. Ideally these should start in the Shelter, you are free to create a sub-module (both of you since you were 354 EG members) there at any time.
