### ISSUE TITLE
Support for Moneta-BP (Java 7 version) in Core or similar?

### ISSUE THREAD

**Issue by keilw** [JadiraOrg/jadira#44]
It seems the Core Library is missing JSR 354 support.
Sometimes misunderstood, but JSR 354  API and RI (Moneta) exist for Java 7 and 8.
So while including the version that requires Java 8 seems fine in a library like "ext" those parts having a minimum version of Java 6 or 7 would do good supporting the Java 6/7 variant of Moneta, too

**Comment by keilw** [comment]
Given this issue https://github.com/JadiraOrg/jadira/issues/42 suggests "ThreetenBP" (an inofficial port of JSR 310 by one of the Spec Leads effectively doin the same as JodaTime) is also supported, there can't be a problem supporting both official RIs of JSR 354 as well ;-)

**Comment by chrisphe** [comment]
310 needs separate integrations for 310 and the backport because the package and class names are different.

For 354, whilst compiled against the Java 8 binary, the resulting user types are made compatible with Java 7 sources using Retroweaver. You should be able to link them to the backport just fine.

**Comment by keilw** [comment]
That makes sense, the "Requires Java 8" note for the "ext" artifact may sound irritating to some users.

**Comment by chrisphe** [comment]
No worries. Where is the note? ... the pom description says "Classes utilising Java 7 and 8 that add Hibernate support for types such as Moneta"

**Comment by keilw** [comment]
It's here for example http://mvnrepository.com/artifact/org.jadira.usertype/usertype.extended
I assume it's retrieved from the POM: "Jadira Usertype Extended For Types Requiring Java 8". The full description is somewhat more neutral, saying "Java 7 and 8".

**Comment by chrisphe** [comment]
Good spot. I've changed the description.
