### ISSUE TITLE
Hibernate 5.0.1 released but does not work with UserType

### ISSUE THREAD

**Issue by benstpierre** [JadiraOrg/jadira#46]
As per this stackoverflow article it appears UserType is incompatible with the newest Hibernate release (5.0.1).

http://stackoverflow.com/questions/32448957/abstractmethoderror-in-sessionfactoryimpl-when-upgrading-to-hibernate-5

Any idea if this is something that will be added?

**Comment by chrisphe** [comment]
Fix in see #41
