### ISSUE TITLE
release Hibernate 5 compatible version?

### ISSUE THREAD

**Issue by The-Alchemist** [JadiraOrg/jadira#49]
Looks like there is Hibernate 5-compatible code available.  Wondering if it's going to be released to Maven Central soon.

Thanks!

**Comment by z0mb1ek** [comment]
would be best

**Comment by pbochis** [comment]
Any updates on this? i need it for an app.

**Comment by chrisphe** [comment]
I'm aim to make a release during the next few days

**Comment by The-Alchemist** [comment]
@chrisphe : you're awesome! :)

**Comment by message** [comment]
Bump

**Comment by awhitford** [comment]
+1

**Comment by theigl** [comment]
+1

I just tested the current master with my application and it works perfectly. Please release ;)

**Comment by chrisphe** [comment]
5.0.0.GA is released. Apologies for the delay, it was meant to be last week, but a change of laptop added a fresh delay.
