### ISSUE TITLE
PersistentDateTime's "databaseZone" and "javaZone" parameters not working as expected

### ISSUE THREAD

**Issue by sguillope** [JadiraOrg/jadira#58]
Assuming the following:
* MySQL 5.6 database
* JDBC over MySQL Connector/J 5.1.39
* Hibernate 5.2.2
* Jadira 6.0.1

We have defined:
* `created_on` column of type `DATETIME`
* Hibernate entity with field `createdOn` defined as follows:
```java
@Column(name = "created_on")
@Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime", 
      parameters = {
          @Parameter(name = "databaseZone", value = "UTC"), 
          @Parameter(name = "javaZone", value = "UTC")
      }
)
private DateTime createdOn;
```

The `databaseZone` and `javaZone` parameters don't seem to work correctly when using [`PersistentDateTime`](https://github.com/JadiraOrg/jadira/blob/293d1b18110c3fa12bc52afe52facfa1d03edc79/usertype.core/src/main/java/org/jadira/usertype/dateandtime/joda/PersistentDateTime.java) and a `DATETIME` column.

We used to use `usertype.jodatime:2.0.1` and had to switch to `usertype.core:6.0.1`  after upgrading to Hibernate 5.2. But now our `createdOn` values are being stored and retrieved based on the JVM's time zone, not the one specified by the parameters.

I think the problem lies in [`TimestampColumnDateTimeMapper`](https://github.com/JadiraOrg/jadira/blob/293d1b18110c3fa12bc52afe52facfa1d03edc79/usertype.core/src/main/java/org/jadira/usertype/dateandtime/joda/columnmapper/TimestampColumnDateTimeMapper.java).
For example this is what happens with its implementation of `fromNonNullValue()`:
```java
public DateTime fromNonNullValue(Timestamp value) { // value: "2016-11-09 04:30:10.0"

    DateTimeZone currentJavaZone = javaZone == null ? ZoneHelper.getDefault() : javaZone; // currentJavaZone: "UTC"

    DateTime dateTime = new DateTime(value.getTime()); // dateTime: "2016-11-09T04:30:10.000-08:00"
    DateTime dateTimeWithZone = dateTime.withZone(currentJavaZone); // dateTimeWithZone: "2016-11-09T12:30:10.000Z"
    
    return dateTimeWithZone;
}
```
Expected result: "2016-11-09T04:30:10.000Z"
Actual result: "2016-11-09T12:30:10.000Z"

In `usertype.jodatime:2.0.1`, which works as expected, the implementation of `TimestampColumnDateTimeMapper` is a bit different:
```java
public DateTime fromNonNullValue(Timestamp value) { // value: "2016-11-09 04:30:10.0"

    DateTimeZone currentDatabaseZone = databaseZone == null ? ZoneHelper.getDefault() : databaseZone; // currentDatabaseZone: "UTC"
    DateTimeZone currentJavaZone = javaZone == null ? ZoneHelper.getDefault() : javaZone; // currentJavaZone: "UTC"

    DateTime dateTime = DATETIME_FORMATTER.withZone(currentDatabaseZone).parseDateTime(value.toString()); // dateTime: "2016-11-09T04:30:10.000Z"
    return dateTime.withZone(currentJavaZone);
    // return: "2016-11-09T04:30:10.000Z"
}
```

The same similar issue happens with the implementation of `toNonNullValue()`.
`usertype.core:6.0.1`
```java
public Timestamp toNonNullValue(DateTime value) { // value: "2016-11-08T21:58:24.864-08:00"
	
    final Timestamp timestamp = new Timestamp(value.getMillis()); // timestamp: "2016-11-09 21:58:24.864"
    return timestamp;
}
```
Expected result: "2016-11-09 05:58:24.864"
Actual result: "2016-11-09 21:58:24.864"

`usertype.jodatime:2.0.1`
```java
public Timestamp toNonNullValue(DateTime value) { // value: "2016-11-08T21:58:24.864-08:00"

    DateTimeZone currentDatabaseZone = databaseZone == null ? ZoneHelper.getDefault() : databaseZone; // currentDatabaseZone: "UTC"

    value = value.withZone(currentDatabaseZone); // value: "2016-11-09T05:58:24.864Z"

    String formattedTimestamp = DATETIME_FORMATTER.print(value); // formattedTimestamp: "2016-11-09 05:58:24.864"
    if (formattedTimestamp.endsWith(".")) {
        formattedTimestamp = formattedTimestamp.substring(0, formattedTimestamp.length() - 1);
    }

    final Timestamp timestamp = Timestamp.valueOf(formattedTimestamp); // timestamp: "2016-11-09 05:58:24.864"
    return timestamp;
}
```

**Comment by jebeaudet** [comment]
Same problem here

**Comment by prateekchachra** [comment]
Hello all,


I've tried working on the issue. There is a new property introduced from Hibernate 5.2 onwards by the name of hibernate.jdbc.time_zone, which hibernate uses to persist the TimeStamp.


While setting this property to the 'databaseZone' property, TimeStamp values are being persisted the way they should be.


Please check into this, this might solve this issue.

**Comment by chrisphe** [comment]
The next build will remove databaseZone in favour of using the Hibernate parameter. You'll still be able to set Java Zone in some cases.

**Comment by prateekchachra** [comment]
Hello chrisphe,


Please consider that the Hibernate parameter applies to all properties related to Date, hence even for properties other than the Jadira Usertype for DateTime, after persistence the Time Zone is applied to all those properties. Even in databases (Like SQL Developer) where persisting time is a compulsion for date-related properties, the time is persisted in the time zone given for the property which can affect a lot of existing features in applications.


Could there be any other solution to this problem without compromising the flexibility that jadira offers with its Time Zone property?

**Comment by chrisphe** [comment]
What I can look at is potentially providing the option to configure (via parameters) a strategy class for a) providing a calendar to use at persistence time, and b) providing an adjuster that will modify the time/timestamp/date prior to persistence. This externalises the 'mangling' from the framework. In the long run, I want to see this dealt with between Hibernate and the database though

**Comment by chrisphe** [comment]
I've reinstated databaseZone, but it now delegates to Hibernate to handle (by proxying the resolution of the TimeZone from the session). This means it overrides the Hibernate property, but it also means the database zone must be specified using JDK TimeZone format in all cases.

**Comment by shahamit** [comment]
I am facing the same issue reported here. Specifying "javaZone" parameter as "UTC" for PersistentDateTime isn't working post hibernate upgrade to 5.4 and usertype.core - 6.0.1.

I tried to go through the solution/workaround but could not follow if there is one. Is there a solution to this issue apart from setting "hibernate.jdbc.time_zone" property which has a global effect? 

Thanks!
